# Generated by Django 4.2.7 on 2023-11-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="total_seat",
            new_name="totalSeat",
        ),
    ]
