# Generated by Django 4.2.7 on 2023-11-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="사용자 계정"
            ),
        ),
    ]
