# Generated by Django 4.2.7 on 2023-11-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fullname",
            new_name="name",
        ),
    ]
