# Generated by Django 4.2.7 on 2023-11-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_fullname_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=20, verbose_name="사용자 계정"),
        ),
    ]
