# Generated by Django 4.2.7 on 2023-11-29 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("seat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="lastDetected",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="마지막 감지"
            ),
        ),
    ]
