# Generated by Django 4.2.7 on 2023-12-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seat", "0002_alter_seat_lastdetected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
