# Generated by Django 4.2.7 on 2023-11-29 12:26

from django.db import migrations, models
import django.utils.timezone
import rent.models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0003_alter_rent_endedat_alter_rent_startedat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="endedAt",
            field=models.DateTimeField(
                default=rent.models.four_hours_from_now, verbose_name="반납 시간"
            ),
        ),
        migrations.AlterField(
            model_name="rent",
            name="startedAt",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="배정 시간"
            ),
        ),
    ]
