# Generated by Django 4.2.7 on 2023-11-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0004_alter_rent_endedat_alter_rent_startedat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rent",
            old_name="user",
            new_name="userId",
        ),
    ]
