# Generated by Django 4.2.7 on 2023-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0005_rename_user_rent_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
